/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppPairingRouteImport } from './routes/_app/pairing'
import { Route as AppSendIndexRouteImport } from './routes/_app/send/index'

const AuthWelcomeLazyRouteImport = createFileRoute('/_auth/welcome')()
const AuthUnlockLazyRouteImport = createFileRoute('/_auth/unlock')()
const AuthSetupPasswordLazyRouteImport = createFileRoute(
  '/_auth/setup-password',
)()
const AuthEnableBiometricLazyRouteImport = createFileRoute(
  '/_auth/enable-biometric',
)()
const AppTransferIndexLazyRouteImport = createFileRoute('/_app/transfer/')()
const AppSettingsIndexLazyRouteImport = createFileRoute('/_app/settings/')()
const AppReceiveIndexLazyRouteImport = createFileRoute('/_app/receive/')()
const AppPairingIndexLazyRouteImport = createFileRoute('/_app/pairing/')()
const AppDevicesIndexLazyRouteImport = createFileRoute('/_app/devices/')()
const AppPairingInputLazyRouteImport = createFileRoute('/_app/pairing/input')()
const AppPairingGenerateLazyRouteImport = createFileRoute(
  '/_app/pairing/generate',
)()

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthWelcomeLazyRoute = AuthWelcomeLazyRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => AuthRoute,
} as any).lazy(() => import('./routes/_auth/welcome.lazy').then((d) => d.Route))
const AuthUnlockLazyRoute = AuthUnlockLazyRouteImport.update({
  id: '/unlock',
  path: '/unlock',
  getParentRoute: () => AuthRoute,
} as any).lazy(() => import('./routes/_auth/unlock.lazy').then((d) => d.Route))
const AuthSetupPasswordLazyRoute = AuthSetupPasswordLazyRouteImport.update({
  id: '/setup-password',
  path: '/setup-password',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth/setup-password.lazy').then((d) => d.Route),
)
const AuthEnableBiometricLazyRoute = AuthEnableBiometricLazyRouteImport.update({
  id: '/enable-biometric',
  path: '/enable-biometric',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth/enable-biometric.lazy').then((d) => d.Route),
)
const AppPairingRoute = AppPairingRouteImport.update({
  id: '/pairing',
  path: '/pairing',
  getParentRoute: () => AppRoute,
} as any)
const AppTransferIndexLazyRoute = AppTransferIndexLazyRouteImport.update({
  id: '/transfer/',
  path: '/transfer/',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/transfer/index.lazy').then((d) => d.Route),
)
const AppSettingsIndexLazyRoute = AppSettingsIndexLazyRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/settings/index.lazy').then((d) => d.Route),
)
const AppReceiveIndexLazyRoute = AppReceiveIndexLazyRouteImport.update({
  id: '/receive/',
  path: '/receive/',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/receive/index.lazy').then((d) => d.Route),
)
const AppPairingIndexLazyRoute = AppPairingIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPairingRoute,
} as any).lazy(() =>
  import('./routes/_app/pairing/index.lazy').then((d) => d.Route),
)
const AppDevicesIndexLazyRoute = AppDevicesIndexLazyRouteImport.update({
  id: '/devices/',
  path: '/devices/',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/devices/index.lazy').then((d) => d.Route),
)
const AppSendIndexRoute = AppSendIndexRouteImport.update({
  id: '/send/',
  path: '/send/',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/send/index.lazy').then((d) => d.Route),
)
const AppPairingInputLazyRoute = AppPairingInputLazyRouteImport.update({
  id: '/input',
  path: '/input',
  getParentRoute: () => AppPairingRoute,
} as any).lazy(() =>
  import('./routes/_app/pairing/input.lazy').then((d) => d.Route),
)
const AppPairingGenerateLazyRoute = AppPairingGenerateLazyRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => AppPairingRoute,
} as any).lazy(() =>
  import('./routes/_app/pairing/generate.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pairing': typeof AppPairingRouteWithChildren
  '/enable-biometric': typeof AuthEnableBiometricLazyRoute
  '/setup-password': typeof AuthSetupPasswordLazyRoute
  '/unlock': typeof AuthUnlockLazyRoute
  '/welcome': typeof AuthWelcomeLazyRoute
  '/pairing/generate': typeof AppPairingGenerateLazyRoute
  '/pairing/input': typeof AppPairingInputLazyRoute
  '/send/': typeof AppSendIndexRoute
  '/devices/': typeof AppDevicesIndexLazyRoute
  '/pairing/': typeof AppPairingIndexLazyRoute
  '/receive/': typeof AppReceiveIndexLazyRoute
  '/settings/': typeof AppSettingsIndexLazyRoute
  '/transfer/': typeof AppTransferIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/enable-biometric': typeof AuthEnableBiometricLazyRoute
  '/setup-password': typeof AuthSetupPasswordLazyRoute
  '/unlock': typeof AuthUnlockLazyRoute
  '/welcome': typeof AuthWelcomeLazyRoute
  '/pairing/generate': typeof AppPairingGenerateLazyRoute
  '/pairing/input': typeof AppPairingInputLazyRoute
  '/send': typeof AppSendIndexRoute
  '/devices': typeof AppDevicesIndexLazyRoute
  '/pairing': typeof AppPairingIndexLazyRoute
  '/receive': typeof AppReceiveIndexLazyRoute
  '/settings': typeof AppSettingsIndexLazyRoute
  '/transfer': typeof AppTransferIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/pairing': typeof AppPairingRouteWithChildren
  '/_auth/enable-biometric': typeof AuthEnableBiometricLazyRoute
  '/_auth/setup-password': typeof AuthSetupPasswordLazyRoute
  '/_auth/unlock': typeof AuthUnlockLazyRoute
  '/_auth/welcome': typeof AuthWelcomeLazyRoute
  '/_app/pairing/generate': typeof AppPairingGenerateLazyRoute
  '/_app/pairing/input': typeof AppPairingInputLazyRoute
  '/_app/send/': typeof AppSendIndexRoute
  '/_app/devices/': typeof AppDevicesIndexLazyRoute
  '/_app/pairing/': typeof AppPairingIndexLazyRoute
  '/_app/receive/': typeof AppReceiveIndexLazyRoute
  '/_app/settings/': typeof AppSettingsIndexLazyRoute
  '/_app/transfer/': typeof AppTransferIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pairing'
    | '/enable-biometric'
    | '/setup-password'
    | '/unlock'
    | '/welcome'
    | '/pairing/generate'
    | '/pairing/input'
    | '/send/'
    | '/devices/'
    | '/pairing/'
    | '/receive/'
    | '/settings/'
    | '/transfer/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/enable-biometric'
    | '/setup-password'
    | '/unlock'
    | '/welcome'
    | '/pairing/generate'
    | '/pairing/input'
    | '/send'
    | '/devices'
    | '/pairing'
    | '/receive'
    | '/settings'
    | '/transfer'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/_app/pairing'
    | '/_auth/enable-biometric'
    | '/_auth/setup-password'
    | '/_auth/unlock'
    | '/_auth/welcome'
    | '/_app/pairing/generate'
    | '/_app/pairing/input'
    | '/_app/send/'
    | '/_app/devices/'
    | '/_app/pairing/'
    | '/_app/receive/'
    | '/_app/settings/'
    | '/_app/transfer/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/welcome': {
      id: '/_auth/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof AuthWelcomeLazyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/unlock': {
      id: '/_auth/unlock'
      path: '/unlock'
      fullPath: '/unlock'
      preLoaderRoute: typeof AuthUnlockLazyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/setup-password': {
      id: '/_auth/setup-password'
      path: '/setup-password'
      fullPath: '/setup-password'
      preLoaderRoute: typeof AuthSetupPasswordLazyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/enable-biometric': {
      id: '/_auth/enable-biometric'
      path: '/enable-biometric'
      fullPath: '/enable-biometric'
      preLoaderRoute: typeof AuthEnableBiometricLazyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/pairing': {
      id: '/_app/pairing'
      path: '/pairing'
      fullPath: '/pairing'
      preLoaderRoute: typeof AppPairingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transfer/': {
      id: '/_app/transfer/'
      path: '/transfer'
      fullPath: '/transfer/'
      preLoaderRoute: typeof AppTransferIndexLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/receive/': {
      id: '/_app/receive/'
      path: '/receive'
      fullPath: '/receive/'
      preLoaderRoute: typeof AppReceiveIndexLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pairing/': {
      id: '/_app/pairing/'
      path: '/'
      fullPath: '/pairing/'
      preLoaderRoute: typeof AppPairingIndexLazyRouteImport
      parentRoute: typeof AppPairingRoute
    }
    '/_app/devices/': {
      id: '/_app/devices/'
      path: '/devices'
      fullPath: '/devices/'
      preLoaderRoute: typeof AppDevicesIndexLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/send/': {
      id: '/_app/send/'
      path: '/send'
      fullPath: '/send/'
      preLoaderRoute: typeof AppSendIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pairing/input': {
      id: '/_app/pairing/input'
      path: '/input'
      fullPath: '/pairing/input'
      preLoaderRoute: typeof AppPairingInputLazyRouteImport
      parentRoute: typeof AppPairingRoute
    }
    '/_app/pairing/generate': {
      id: '/_app/pairing/generate'
      path: '/generate'
      fullPath: '/pairing/generate'
      preLoaderRoute: typeof AppPairingGenerateLazyRouteImport
      parentRoute: typeof AppPairingRoute
    }
  }
}

interface AppPairingRouteChildren {
  AppPairingGenerateLazyRoute: typeof AppPairingGenerateLazyRoute
  AppPairingInputLazyRoute: typeof AppPairingInputLazyRoute
  AppPairingIndexLazyRoute: typeof AppPairingIndexLazyRoute
}

const AppPairingRouteChildren: AppPairingRouteChildren = {
  AppPairingGenerateLazyRoute: AppPairingGenerateLazyRoute,
  AppPairingInputLazyRoute: AppPairingInputLazyRoute,
  AppPairingIndexLazyRoute: AppPairingIndexLazyRoute,
}

const AppPairingRouteWithChildren = AppPairingRoute._addFileChildren(
  AppPairingRouteChildren,
)

interface AppRouteChildren {
  AppPairingRoute: typeof AppPairingRouteWithChildren
  AppSendIndexRoute: typeof AppSendIndexRoute
  AppDevicesIndexLazyRoute: typeof AppDevicesIndexLazyRoute
  AppReceiveIndexLazyRoute: typeof AppReceiveIndexLazyRoute
  AppSettingsIndexLazyRoute: typeof AppSettingsIndexLazyRoute
  AppTransferIndexLazyRoute: typeof AppTransferIndexLazyRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppPairingRoute: AppPairingRouteWithChildren,
  AppSendIndexRoute: AppSendIndexRoute,
  AppDevicesIndexLazyRoute: AppDevicesIndexLazyRoute,
  AppReceiveIndexLazyRoute: AppReceiveIndexLazyRoute,
  AppSettingsIndexLazyRoute: AppSettingsIndexLazyRoute,
  AppTransferIndexLazyRoute: AppTransferIndexLazyRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthEnableBiometricLazyRoute: typeof AuthEnableBiometricLazyRoute
  AuthSetupPasswordLazyRoute: typeof AuthSetupPasswordLazyRoute
  AuthUnlockLazyRoute: typeof AuthUnlockLazyRoute
  AuthWelcomeLazyRoute: typeof AuthWelcomeLazyRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthEnableBiometricLazyRoute: AuthEnableBiometricLazyRoute,
  AuthSetupPasswordLazyRoute: AuthSetupPasswordLazyRoute,
  AuthUnlockLazyRoute: AuthUnlockLazyRoute,
  AuthWelcomeLazyRoute: AuthWelcomeLazyRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
